# Generated by Django 4.2.4 on 2023-08-07 11:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lesson_title', models.TextField(max_length=300)),
                ('site_url', models.TextField(max_length=300)),
                ('image', models.TextField()),
                ('price', models.IntegerField()),
                ('field', models.CharField(max_length=100)),
            ],
        ),
    ]
